spring.datasource.url: jdbc:sqlserver://localhost;databaseName=ms_test
spring.datasource.username: root
spring.datasource.password: 1234
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.dialect: org.hibernate.dialect.MsSQL8Dialect
