spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hello
spring.datasource.username: root
spring.datasource.password: Password21#$
spring.jpa.show-sql: true